import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PrimroseVT',
  description: 'Generated by create next app',
  faviconUrl: '/assets/Primcon.png',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>{metadata.title}</title>
        <link rel="icon" href={metadata.faviconUrl} />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
